env:
  global:
  - POSTGRES_DB=travis_ci_test
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=
  - POSTGRES_HOST=localhost
  - POSTGRES_PORT=5432
language: python
python: 3.8
branches:
  only:
  - master
before_install:
- pip install poetry
install:
- make install
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- make migrate
script:
- make lint
deploy:
  provider: heroku
  api_key:
    secure: XKwJ2BKQLWvDXa4vsqaIEw197NYCpD02d7h8hs9vtugSE1UDie2OqcnxoEudqYtz39G27DekgTXCTUQYR1PKmTBz0/V2En/tzaHFKMOqV+mUY5a1cGGWhC9SYObgT2U70deeyaN3ErsEhyWemYFxDgIq5uadl20d5esslkG7LFbnO/iIRjMWlVddJCCo0PXdmtmdkdEbzvGQOV/WHB5MvrnQQwBpKc8avfDfk6rEr2PNYhv+dmk1yUMbaaOzmsHgYnwfrEHj/8FRxjpNy6hGQNZlW6aX/kr+uztjR5gUuxSqGPah2YmqR+IffKVu3fRbCySSX7AedR9qLCb6NUO/qXwo/AG9/Hmuu5U6g1W9j+bNQKUj8QVIID7mXKcEsl2K+We2xMXfhW2rtRFuED0ZhnIAelIpAfZbB6x3rwYj8Nj32lGJAu2l4xUphCEcfZVaoSYdmEguYxlXy81bzMNtnT94UlE3FTFjlX1BDBTbY6F9x2kYbhfQwZ/IQYSyFe4GZ4zCcXHCaowI4jaY5xced3+smFEAYk+CcqB7e6xUyHv+SxFeDZN4xxVgeYRB0I0+65IIUU+D0p0/7QBxqLwEDZQUB5NvZc/aFFrEuEctVACo7GnoFDpcDP0OEzCm/4220/56fdy0LHuN7pZDx1w+1Cn1dObkAm+6MUmhvhnUmwA=
  app: new-words-backend
  on:
    repo: alexofechoes/new-words-backend
  skip_cleanup: true
