env:
  global:
  - POSTGRES_DB=travis_ci_test
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=
  - POSTGRES_HOST=localhost
  - POSTGRES_PORT=5432
language: python
python: 3.8
branches:
  only:
  - master
before_install:
- pip install poetry
install:
- make install
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- make migrate
script:
- make lint
deploy:
  provider: heroku
  app: new-words-backend
  api_key:
    secure: WpV69rMS5WjvlUgnMCHY28JfA22bkXw6+2q0iVv6PNmRQmA6/yTBTvXQ5vCyeVy7uVo4nvD5IBfPsPSDBQqK6xjZ2TYeYceZFYe2ihfKG5m16pjilllIwYNG0aW7/9yOVOkdViNjuPTn/GYwsyFZWGL76pdDBjSqXYnfLNfD88DS9rv5InIcYr8iA49Cvsa7YfVz7tgKrQV7MEdjFk4ej62GhRhS5pT18mf/vJX7DFefFC4gkBHbNzsyD16SNIXf4AoRnhcBYlTGcifJ+Ta9DTF7wEDAlfC48ZPPTs9CRQflYFFT5vBj/xhrATLZulqrRB8ZExqRkQOzi6wCHlHBHj2QhZjOcz1+toEFfSvbIuTJFStDubiYt/ibkRGsfRNCPMB4QeXQU4D03JZFr5WqkZf5JL2S/hAxtljlcJGtKOkFsCz+bVduyHc9FJ059sm4Pe4A5K+Cu+sIUFjywsCVUKmEd4WOxdNahQQRI9E64uJQa3efMkTrAyKMk6mnBZjK6iSIk6wbF3ZfzQde8rwiSbkGrgXsEN0sVJUL4Qfi5i94jhd4fgRryCniMqPweoK35/CxaaqhzNzSfoq9ianyEpTrizXd2KavJOjkjpsi2/oqdtgSP50OQAy/PjnoFBaeg0A0XlTRhDXLTMjOF1WCBH9k9ickRK/bzk/uDYUAQF4=
