version: '3'

services:
  # app:
  #   build: .
  #   command: poetry run ./manage.py runserver 0.0.0.0:8888
  #   volumes:
  #     - .:/code
  #   env_file:
  #     - .env
  #   ports:
  #     - 8888:8888
  #   depends_on: 
  #     - db
  
  db:
    image: postgres:10.8
    environment:
      POSTGRES_USER: "newwords"
      POSTGRES_PASSWORD: "newwords"
      POSTGRES_DB: "newwords"
    ports:
        - 5432:5432
    volumes:
        - ./.docker/postgres/newwords_db:/var/lib/postgresql
    network_mode: host
