version: '3'

services:
  app:
    build: .
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
      - migrate

  db:
    image: postgres:10.8
    env_file:
      - .env
    ports:
        - 5432:5432
    volumes:
        - ./.docker/postgres/newwords_db:/var/lib/postgresql

  migrate:
    build: .
    command: python src/manage.py migrate
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
