# Generated by Django 2.2.7 on 2019-11-10 18:43

from django.db import migrations

import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('new_words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='state',
            field=django_fsm.FSMField(default='new', max_length=50, protected=True),
        ),
    ]
