# Generated by Django 2.2.7 on 2019-11-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_words', '0002_text_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
